name: aq_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # core
  - numpy
  - pandas

  # netcdf backends (avoid xarray engine issues)
  - xarray
  - netcdf4
  - h5netcdf

  # geospatial stack (stable I/O for GPKG + raster)
  - geopandas
  - pyogrio
  - fiona
  - gdal
  - pyproj
  - shapely
  - rasterio
  - rioxarray

  # plotting
  - matplotlib

  # notebook
  - jupyterlab
  - ipykernel

  # testing
  - pytest