name: aq_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # core
  - numpy
  - pandas

  # geospatial / raster stack
  - geopandas
  - xarray
  - rasterio
  - rioxarray

  # plotting (for notebook demo)
  - matplotlib

  # notebook
  - jupyterlab
  - ipykernel
